import Head from 'next/head'
import Posts from '../components/Posts'

export default function Home({posts}) {
  return (
    <>
      <Head>
        <title>Nextjs Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Posts posts={posts} />
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=10`)
  const posts = await res.json()

  return {
    props: {
      posts
    }
  }
}